language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
