language: php

before_script:
  - rm composer.lock
  - travis_retry composer update --prefer-dist $DEPENDENCIES

jobs:
  include:
    - stage: Test
      php: 7.2
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit

    - stage: Test
      php: 7.2
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit

    - stage: Test
      php: 7.3
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit

    - stage: Test
      php: 7.3
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit

    - stage: Test Compatibility
      php: 7.2
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      php: 7.2
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      php: 7.3
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      php: 7.3
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit test/compat

    - stage: Check Demo Scripts
      php: 7.2
      env: DEPENDENCIES=""
      script: test/demo/check-demo.sh

    - stage: Check Demo Scripts
      php: 7.2
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: test/demo/check-demo.sh

    - stage: Check Demo Scripts
      php: 7.3
      env: DEPENDENCIES=""
      script: test/demo/check-demo.sh

    - stage: Check Demo Scripts
      php: 7.3
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: test/demo/check-demo.sh

    - stage: Check Coding Standard
      php: 7.3
      env: DEPENDENCIES=""
      before_script:
        - travis_retry composer install
      script: vendor/bin/phpcs

    - stage: Static Analysis
      php: 7.2
      env: DEPENDENCIES=""
      before_script:
        - travis_retry composer require --dev --prefer-dist --prefer-stable phpstan/phpstan:^0.11.5
      script: vendor/bin/phpstan analyse

    - stage: Static Analysis
      php: 7.2
      env: DEPENDENCIES=""
      before_script:
        - travis_retry composer require --dev --prefer-dist --prefer-stable vimeo/psalm:2.0.0
      script: vendor/bin/psalm

    - stage: Run benchmarks
      php: 7.2
      env: DEPENDENCIES=""
      before_script:
        - travis_retry composer require --dev --prefer-dist --prefer-stable phpbench/phpbench:^0.16.9
      script: ./vendor/bin/phpbench run --progress=dots --iterations=1

    - stage: Upload Coverage
      php: 7.2
      env: DEPENDENCIES=""
      before_script:
        - travis_retry composer update --prefer-dist $DEPENDENCIES
        - wget https://scrutinizer-ci.com/ocular.phar
      script:
        - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml

cache:
  directories:
    - $HOME/.composer/cache
